services:
  - type: web
    name: shopc2c-server
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: MONGODB_URI
        sync: false
